export const sampleObj={
    "location": {
        "name": "Pune",
        "region": "Para",
        "country": "Brazil",
        "lat": 1.9667,
        "lon": -54.9167,
        "tz_id": "America/Santarem",
        "localtime_epoch": 1743049695,
        "localtime": "2025-03-27 01:28"
    },
    "current": {
        "last_updated_epoch": 1743048900,
        "last_updated": "2025-03-27 01:15",
        "temp_c": 20.8,
        "is_day": 0,
        "wind_kph": 5.8,
        "wind_dir": "NE",
        "humidity": 98,
        "cloud": 100,
        "windchill_c": 20.8,
        "heatindex_c": 20.8,
        "dewpoint_c": 20.5,
        "uv": 0.0,
        "gust_kph": 9.3,
        "air_quality": {
            "co": 258.446,
            "no2": 0.168,
            "o3": 24.0,
            "so2": 0.0,
            "pm2_5": 8.391,
            "pm10": 14.097,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    }
}

export const forcastObj={
  "location": {
      "name": "Pune",
      "region": "Maharashtra",
      "country": "India",
      "lat": 18.5333,
      "lon": 73.8667,
      "tz_id": "Asia/Kolkata",
      "localtime_epoch": 1743050433,
      "localtime": "2025-03-27 10:10"
  },
  "forecast": {
      "forecastday": [
          {
              "date": "2025-10-01",
              "date_epoch": 1759276800,
              "day": {
                  "maxtemp_c": 29.5,
                  "mintemp_c": 21.7,
                  "maxwind_kph": 13.0,
                  "avghumidity": 77.0,
                  "uv": 5.0
              },
              "astro": {
                  "sunrise": "06:25 AM",
                  "sunset": "06:23 PM",
                  "moonrise": "02:18 PM",
                  "moonset": "12:31 AM",
                  "moon_phase": "Waxing Gibbous",
                  "moon_illumination": 58
              },
              "hour": [
                  {
                      "time_epoch": 1759257000,
                      "time": "2025-10-01 00:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.8,
                      "wind_dir": "SW",
                      "humidity": 87,
                      "cloud": 50,
                      "windchill_c": 22.4,
                      "heatindex_c": 24.4,
                      "dewpoint_c": 20.1,
                      "will_it_rain": 1,
                      "chance_of_rain": 76,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759260600,
                      "time": "2025-10-01 01:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.5,
                      "wind_dir": "SSW",
                      "humidity": 87,
                      "cloud": 45,
                      "windchill_c": 22.2,
                      "heatindex_c": 24.3,
                      "dewpoint_c": 19.9,
                      "will_it_rain": 1,
                      "chance_of_rain": 86,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759264200,
                      "time": "2025-10-01 02:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.5,
                      "wind_dir": "SW",
                      "humidity": 87,
                      "cloud": 43,
                      "windchill_c": 22.0,
                      "heatindex_c": 23.9,
                      "dewpoint_c": 19.7,
                      "will_it_rain": 0,
                      "chance_of_rain": 70,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759267800,
                      "time": "2025-10-01 03:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.1,
                      "wind_dir": "SSW",
                      "humidity": 87,
                      "cloud": 51,
                      "windchill_c": 21.8,
                      "heatindex_c": 23.4,
                      "dewpoint_c": 19.5,
                      "will_it_rain": 0,
                      "chance_of_rain": 64,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759271400,
                      "time": "2025-10-01 04:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.5,
                      "wind_dir": "SSW",
                      "humidity": 85,
                      "cloud": 48,
                      "windchill_c": 22.6,
                      "heatindex_c": 24.1,
                      "dewpoint_c": 19.8,
                      "will_it_rain": 1,
                      "chance_of_rain": 75,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759275000,
                      "time": "2025-10-01 05:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.8,
                      "wind_dir": "SSW",
                      "humidity": 82,
                      "cloud": 48,
                      "windchill_c": 23.0,
                      "heatindex_c": 24.8,
                      "dewpoint_c": 20.5,
                      "will_it_rain": 1,
                      "chance_of_rain": 77,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759278600,
                      "time": "2025-10-01 06:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 7.2,
                      "wind_dir": "SSW",
                      "humidity": 80,
                      "cloud": 36,
                      "windchill_c": 23.2,
                      "heatindex_c": 25.1,
                      "dewpoint_c": 20.6,
                      "will_it_rain": 1,
                      "chance_of_rain": 84,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759282200,
                      "time": "2025-10-01 07:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 7.9,
                      "wind_dir": "S",
                      "humidity": 75,
                      "cloud": 36,
                      "windchill_c": 24.2,
                      "heatindex_c": 26.4,
                      "dewpoint_c": 20.8,
                      "will_it_rain": 0,
                      "chance_of_rain": 62,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759285800,
                      "time": "2025-10-01 08:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 7.9,
                      "wind_dir": "SSE",
                      "humidity": 70,
                      "cloud": 43,
                      "windchill_c": 25.7,
                      "heatindex_c": 28.0,
                      "dewpoint_c": 20.8,
                      "will_it_rain": 1,
                      "chance_of_rain": 86,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759289400,
                      "time": "2025-10-01 09:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 8.6,
                      "wind_dir": "SSE",
                      "humidity": 64,
                      "cloud": 39,
                      "windchill_c": 27.0,
                      "heatindex_c": 29.3,
                      "dewpoint_c": 20.7,
                      "will_it_rain": 1,
                      "chance_of_rain": 83,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759293000,
                      "time": "2025-10-01 10:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 9.4,
                      "wind_dir": "SSE",
                      "humidity": 63,
                      "cloud": 44,
                      "windchill_c": 28.0,
                      "heatindex_c": 30.4,
                      "dewpoint_c": 20.6,
                      "will_it_rain": 1,
                      "chance_of_rain": 81,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759296600,
                      "time": "2025-10-01 11:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 9.4,
                      "wind_dir": "S",
                      "humidity": 62,
                      "cloud": 48,
                      "windchill_c": 28.7,
                      "heatindex_c": 31.1,
                      "dewpoint_c": 20.5,
                      "will_it_rain": 1,
                      "chance_of_rain": 81,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759300200,
                      "time": "2025-10-01 12:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 9.7,
                      "wind_dir": "SSW",
                      "humidity": 61,
                      "cloud": 53,
                      "windchill_c": 29.4,
                      "heatindex_c": 31.9,
                      "dewpoint_c": 20.4,
                      "will_it_rain": 1,
                      "chance_of_rain": 88,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759303800,
                      "time": "2025-10-01 13:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 10.1,
                      "wind_dir": "SW",
                      "humidity": 63,
                      "cloud": 58,
                      "windchill_c": 28.9,
                      "heatindex_c": 31.4,
                      "dewpoint_c": 20.5,
                      "will_it_rain": 1,
                      "chance_of_rain": 80,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759307400,
                      "time": "2025-10-01 14:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 10.1,
                      "wind_dir": "SW",
                      "humidity": 66,
                      "cloud": 68,
                      "windchill_c": 28.2,
                      "heatindex_c": 30.6,
                      "dewpoint_c": 20.6,
                      "will_it_rain": 0,
                      "chance_of_rain": 68,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759311000,
                      "time": "2025-10-01 15:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 10.1,
                      "wind_dir": "SW",
                      "humidity": 70,
                      "cloud": 65,
                      "windchill_c": 27.6,
                      "heatindex_c": 29.9,
                      "dewpoint_c": 20.8,
                      "will_it_rain": 1,
                      "chance_of_rain": 83,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759314600,
                      "time": "2025-10-01 16:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 10.1,
                      "wind_dir": "SW",
                      "humidity": 74,
                      "cloud": 68,
                      "windchill_c": 26.6,
                      "heatindex_c": 28.9,
                      "dewpoint_c": 20.8,
                      "will_it_rain": 0,
                      "chance_of_rain": 67,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759318200,
                      "time": "2025-10-01 17:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 9.7,
                      "wind_dir": "WSW",
                      "humidity": 79,
                      "cloud": 61,
                      "windchill_c": 25.3,
                      "heatindex_c": 27.2,
                      "dewpoint_c": 20.9,
                      "will_it_rain": 1,
                      "chance_of_rain": 89,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759321800,
                      "time": "2025-10-01 18:00",
                      "temp_c": 24.8,
                      "is_day": 1,
                      "wind_kph": 8.6,
                      "wind_dir": "WSW",
                      "humidity": 84,
                      "cloud": 53,
                      "windchill_c": 24.1,
                      "heatindex_c": 26.1,
                      "dewpoint_c": 20.8,
                      "will_it_rain": 1,
                      "chance_of_rain": 86,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759325400,
                      "time": "2025-10-01 19:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 8.3,
                      "wind_dir": "SW",
                      "humidity": 85,
                      "cloud": 55,
                      "windchill_c": 23.5,
                      "heatindex_c": 25.5,
                      "dewpoint_c": 20.6,
                      "will_it_rain": 1,
                      "chance_of_rain": 73,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759329000,
                      "time": "2025-10-01 20:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 7.6,
                      "wind_dir": "SW",
                      "humidity": 86,
                      "cloud": 54,
                      "windchill_c": 23.1,
                      "heatindex_c": 25.2,
                      "dewpoint_c": 20.5,
                      "will_it_rain": 1,
                      "chance_of_rain": 76,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759332600,
                      "time": "2025-10-01 21:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.8,
                      "wind_dir": "SW",
                      "humidity": 86,
                      "cloud": 56,
                      "windchill_c": 22.8,
                      "heatindex_c": 24.9,
                      "dewpoint_c": 20.4,
                      "will_it_rain": 1,
                      "chance_of_rain": 73,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759336200,
                      "time": "2025-10-01 22:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.5,
                      "wind_dir": "SSW",
                      "humidity": 86,
                      "cloud": 55,
                      "windchill_c": 22.5,
                      "heatindex_c": 24.7,
                      "dewpoint_c": 20.2,
                      "will_it_rain": 0,
                      "chance_of_rain": 69,
                      "uv": 0.0
                  },
                  {
                      "time_epoch": 1759339800,
                      "time": "2025-10-01 23:00",
                      "temp_c": 24.8,
                      "is_day": 0,
                      "wind_kph": 6.5,
                      "wind_dir": "SSW",
                      "humidity": 87,
                      "cloud": 53,
                      "windchill_c": 22.4,
                      "heatindex_c": 24.7,
                      "dewpoint_c": 20.0,
                      "will_it_rain": 1,
                      "chance_of_rain": 76,
                      "uv": 0.0
                  }
              ]
          }
      ]
  }
}